import { CaseStudy, L, LS } from "./types";

export const deliveryWorkers: CaseStudy = {
  id: "delivery-workers",
  category: "labour",
  event: L("China moves to extend social insurance to food-delivery riders", "中国拟将社会保险扩展至外卖骑手"),
  score: 91,
  potential: [
    { label: L("Theory richness", "理论丰富度"), value: 92 },
    { label: L("Data availability", "数据可得性"), value: 83 },
    { label: L("Debate / contestability", "争议性"), value: 90 },
    { label: L("Policy relevance", "政策相关性"), value: 94 },
  ],
  summary: {
    oneLine: L(
      "Mandating platform contributions to riders' social insurance internalises a real externality but, in a monopsonistic and price-elastic market, shifts part of the cost back onto riders and consumers.",
      "强制平台为骑手缴纳社会保险使真实外部性内部化，但在买方垄断且价格弹性较高的市场中，部分成本会转嫁回骑手与消费者。"
    ),
    overview: L(
      "Platforms classify riders as independent contractors, avoiding pension and injury contributions while exerting algorithmic control over pay and dispatch — a principal-agent and information-asymmetry problem. Extending insurance raises labour costs; who ultimately pays depends on labour-supply elasticity, platform market power (monopsony) and how costs pass through to delivery fees.",
      "平台将骑手归类为独立承包人，规避养老金与工伤缴费，同时通过算法掌控薪酬与派单——这是委托代理与信息不对称问题。扩展保险会抬高用工成本；最终由谁承担取决于劳动供给弹性、平台市场势力（买方垄断）以及成本向配送费的转嫁程度。"
    ),
    matters: LS(
      ["It reframes gig work through labour-market, principal-agent and market-failure theory.", "它用劳动力市场、委托代理与市场失灵理论重新审视零工经济。"],
      ["It tests who truly bears a mandated benefit — firms, workers or consumers.", "它检验强制福利的真正承担者——企业、劳动者还是消费者。"],
      ["It touches informality, monopsony and the future of platform labour.", "它涉及非正规化、买方垄断与平台用工的未来。"],
    ),
    stakeholders: LS(["Delivery riders", "外卖骑手"], ["Platforms", "平台"], ["Consumers", "消费者"], ["Government / social-security funds", "政府与社保基金"], ["Restaurants", "餐厅"]),
  },
  factors: [
    {
      key: "bg.economic",
      summary: L("Gig riders fall outside formal employment, so injury and pension risk is uninsured.", "零工骑手处于正式雇佣之外，工伤与养老风险无保险覆盖。"),
      detail: L("Contractor status lets platforms avoid payroll contributions; risk is borne privately by riders and, when they are injured, by public health systems — a cost not priced into delivery fees.", "承包人身份使平台规避社保缴费；风险由骑手私人承担，受伤时则由公共医疗体系承担——这一成本未计入配送费。"),
      statistics: LS(["Tens of millions of gig riders nationally", "全国数千万零工骑手"], ["Most lack work-injury insurance", "多数缺乏工伤保险"]),
      stakeholders: LS(["Riders", "骑手"], ["Public health system", "公共医疗体系"]),
      essayIdeas: LS(["Model uninsured injury risk as a negative externality on the state.", "把未保险的工伤风险建模为对国家的负外部性。"]),
      arguments: LS(["Mandated insurance internalises the social cost of injuries.", "强制保险使工伤的社会成本内部化。"]),
      counterarguments: LS(["It may push riders into fewer, costlier opportunities.", "它可能使骑手机会变少、成本更高。"]),
    },
    {
      key: "bg.technological",
      summary: L("Algorithmic management sets pay and dispatch with little transparency.", "算法管理在不透明的情况下设定薪酬与派单。"),
      detail: L("Platforms hold information riders lack (demand, routing, pay rules), creating asymmetry and a principal-agent gap where incentives may not align with rider welfare or safety.", "平台掌握骑手所缺的信息（需求、路径、薪酬规则），造成不对称与委托代理缺口，激励可能与骑手福利或安全不一致。"),
      statistics: LS(["Pay-per-order incentivises speed over safety", "按单计酬激励抢速度而非安全"]),
      stakeholders: LS(["Riders", "骑手"], ["Platform engineers", "平台工程师"]),
      essayIdeas: LS(["Use principal-agent theory to explain unsafe incentives.", "用委托代理理论解释不安全的激励。"]),
      arguments: LS(["Regulation can correct misaligned incentives.", "监管可纠正错配的激励。"]),
      counterarguments: LS(["Heavy rules may reduce flexibility riders value.", "过重规则可能削弱骑手所看重的灵活性。"]),
    },
    {
      key: "bg.social",
      summary: L("Flexibility vs security is the core social trade-off.", "灵活性与保障之间是核心的社会权衡。"),
      detail: L("Many riders value flexible hours and entry without credentials; formalisation may raise security but reduce the low-barrier flexibility that drew them in.", "许多骑手看重灵活工时与无门槛进入；正规化或提升保障，却可能削弱吸引他们的低门槛灵活性。"),
      statistics: LS(["A large share are migrant or transitional workers", "相当比例为流动或过渡性劳动者"]),
      stakeholders: LS(["Riders", "骑手"], ["Families", "家庭"]),
      essayIdeas: LS(["Is flexibility a genuine preference or a constrained choice?", "灵活性是真实偏好还是受约束的选择？"]),
      arguments: LS(["Security reduces precarity for vulnerable workers.", "保障降低弱势劳动者的不稳定性。"]),
      counterarguments: LS(["Formalisation may exclude those needing easy entry.", "正规化可能排斥需要便捷进入的人群。"]),
    },
    {
      key: "bg.political",
      summary: L("Worker welfare and social stability are policy priorities.", "劳动者福利与社会稳定是政策优先项。"),
      detail: L("Visible protection of gig workers builds legitimacy; but regulators must avoid harming a sector that absorbs significant employment.", "对零工劳动者的显性保护增强合法性；但监管者须避免损害一个吸纳大量就业的部门。"),
      statistics: LS(["Delivery is a major urban employment buffer", "外卖是重要的城市就业缓冲"]),
      stakeholders: LS(["Government", "政府"], ["Platforms", "平台"]),
      essayIdeas: LS(["Balance worker protection against employment levels.", "在劳动者保护与就业水平之间取得平衡。"]),
      arguments: LS(["State has a duty to protect basic security.", "国家有责任保护基本保障。"]),
      counterarguments: LS(["Over-regulation could shrink available work.", "过度监管可能减少可得工作。"]),
    },
    {
      key: "bg.legal",
      summary: L("Employment classification is the legal pivot.", "雇佣身份认定是法律枢纽。"),
      detail: L("Whether riders are employees, contractors or a third category determines obligations; ambiguity invites disputes and avoidance.", "骑手是雇员、承包人还是第三类，决定了义务；模糊会招致争议与规避。"),
      statistics: LS(["Courts increasingly scrutinise platform control", "法院日益审视平台的控制权"]),
      stakeholders: LS(["Labour courts", "劳动法院"], ["Platforms", "平台"]),
      essayIdeas: LS(["Should a third 'dependent contractor' status exist?", "是否应设第三类“从属承包人”身份？"]),
      arguments: LS(["Clear status reduces avoidance.", "清晰身份减少规避。"]),
      counterarguments: LS(["Rigid categories fit gig work poorly.", "僵硬的分类难以契合零工。"]),
    },
    {
      key: "bg.cultural",
      summary: L("Attitudes to gig work shape acceptance of reform.", "对零工的态度影响改革的接受度。"),
      detail: L("Public sympathy for riders raises support for protection but also tolerance for slightly higher delivery prices.", "公众对骑手的同情提升对保护的支持，也提高对配送价格略升的容忍度。"),
      statistics: LS(["High-profile injury cases shift opinion", "高曝光工伤事件改变舆论"]),
      stakeholders: LS(["Consumers", "消费者"], ["Media", "媒体"]),
      essayIdeas: LS(["How do norms change willingness to pay?", "规范如何改变支付意愿？"]),
      arguments: LS(["Social norms can sustain higher fees.", "社会规范可支撑更高费用。"]),
      counterarguments: LS(["Price sensitivity may dominate in practice.", "实践中价格敏感性可能主导。"]),
    },
    {
      key: "bg.historical",
      summary: L("Parallels with earlier informal-sector formalisation.", "与早前非正规部门正规化的相似之处。"),
      detail: L("Past efforts to extend social insurance to informal workers offer lessons on compliance, evasion and coverage.", "以往将社保扩展至非正规劳动者的努力，为合规、规避与覆盖提供了经验。"),
      statistics: LS(["Informal-sector coverage historically lags", "非正规部门覆盖历来滞后"]),
      stakeholders: LS(["Policy historians", "政策史学者"]),
      essayIdeas: LS(["Use prior reforms as comparators.", "以过往改革为对照。"]),
      arguments: LS(["Phased coverage has worked before.", "分阶段覆盖此前奏效。"]),
      counterarguments: LS(["Evasion often undermines coverage.", "规避常削弱覆盖。"]),
    },
    {
      key: "bg.environmental",
      summary: L("Delivery density affects congestion and emissions.", "配送密度影响拥堵与排放。"),
      detail: L("Labour-cost changes alter delivery volumes and modes, with secondary effects on urban traffic and emissions.", "用工成本变化改变配送量与方式，对城市交通与排放产生次生影响。"),
      statistics: LS(["Two-wheelers dominate last-mile delivery", "两轮车主导最后一公里配送"]),
      stakeholders: LS(["City planners", "城市规划者"]),
      essayIdeas: LS(["Link labour policy to urban externalities.", "把劳动政策与城市外部性联系起来。"]),
      arguments: LS(["Fewer, safer trips can cut harm.", "更少且更安全的行程可减少危害。"]),
      counterarguments: LS(["Effects are second-order and uncertain.", "效应是次级且不确定的。"]),
    },
  ],
  timeline: [
    { date: "2014–2019", kind: "cause", title: L("Platform delivery scales rapidly", "平台外卖迅速扩张"), detail: L("App-based delivery grows into a mass labour market built on contractor classification.", "基于 App 的外卖成长为以承包人身份为基础的大规模劳动力市场。") },
    { date: "2020–2022", kind: "cause", title: L("Algorithmic pressure & injuries surface", "算法压力与工伤显现"), detail: L("Investigations highlight unsafe pay incentives and uninsured injury risk.", "调查揭示不安全的薪酬激励与无保险的工伤风险。") },
    { date: "2024–2025", kind: "trigger", title: L("Pilot protections introduced", "试点保护出台"), detail: L("Localised injury-insurance pilots test platform contributions.", "地方性工伤保险试点检验平台缴费。") },
    { date: "2026-06", kind: "milestone", title: L("National social-insurance extension proposed", "拟全国扩展社会保险"), detail: L("Rules would require pension and injury contributions for riders nationwide.", "新规将要求全国为骑手缴纳养老金与工伤保险。") },
    { date: "2026-2028", kind: "future", title: L("Cost pass-through & restructuring", "成本转嫁与重组"), detail: L("Platforms may adjust pay, fees or rider numbers; some shift to scheduled models.", "平台或调整薪酬、费用或骑手数量；部分转向排班模式。") },
    { date: "2029+", kind: "future", title: L("New equilibrium for platform labour", "平台用工的新均衡"), detail: L("Coverage, employment and prices settle, revealing the true incidence of the mandate.", "覆盖率、就业与价格趋稳，显现强制规定的真实归宿。") },
  ],
  theories: [
    { name: L("Labour Market Theory (with Monopsony)", "劳动力市场理论（含买方垄断）"), match: 95, diagram: "labourMarket", explanation: L("Wages and employment follow labour demand and supply; with monopsony, platforms set pay below the competitive level.", "工资与就业由劳动供需决定；在买方垄断下，平台将薪酬压低于竞争水平。"), relevance: L("Determines whether a mandate cuts jobs or merely transfers surplus from platforms.", "决定强制规定是减少就业，还是仅将剩余从平台转移出来。"), strengths: LS(["Predicts employment & wage effects", "预测就业与工资效应"], ["Monopsony explains low gig pay", "买方垄断解释零工低薪"]), weaknesses: LS(["Elasticities are hard to pin down", "弹性难以确定"]) },
    { name: L("Principal–Agent Problem", "委托代理问题"), match: 92, diagram: "supplyDemand", explanation: L("When the platform (principal) cannot perfectly observe rider (agent) effort, pay schemes shape behaviour — sometimes toward unsafe speed.", "当平台（委托人）无法完美观察骑手（代理人）努力时，薪酬方案塑造行为——有时趋向不安全的抢速度。"), relevance: L("Explains why algorithmic pay can harm safety and why rules may realign incentives.", "解释算法薪酬为何损害安全，以及规则为何可能重新对齐激励。"), strengths: LS(["Links contracts to behaviour", "把合约与行为联系起来"]), weaknesses: LS(["Hard to measure effort & risk", "努力与风险难以测量"]) },
    { name: L("Information Asymmetry", "信息不对称"), match: 88, diagram: "supplyDemand", explanation: L("Platforms hold information riders lack about demand, routing and pay, tilting bargaining power.", "平台掌握骑手所缺的需求、路径与薪酬信息，使议价权倾斜。"), relevance: L("Justifies transparency rules as a remedy for a market failure.", "为以透明度规则纠正市场失灵提供依据。"), strengths: LS(["Identifies a clear failure", "识别明确的失灵"]), weaknesses: LS(["Disclosure may be gamed", "披露可能被操弄"]) },
    { name: L("Externalities", "外部性"), match: 86, diagram: "externalities", explanation: L("Uninsured injuries impose costs on public health systems — a negative externality of the current model.", "未保险的工伤将成本施加于公共医疗体系——现行模式的负外部性。"), relevance: L("Mandated contributions internalise this external cost.", "强制缴费使这一外部成本内部化。"), strengths: LS(["Clear welfare rationale", "清晰的福利依据"]), weaknesses: LS(["External cost hard to value", "外部成本难以估值"]) },
    { name: L("Efficiency Wage Theory", "效率工资理论"), match: 78, diagram: "labourMarket", explanation: L("Paying above-market can raise effort, retention and safety, partly offsetting higher costs.", "高于市场的薪酬可提升努力、留存与安全，部分抵消更高成本。"), relevance: L("Suggests mandated benefits may improve productivity, not just cost.", "表明强制福利可能提升生产率，而不仅是成本。"), strengths: LS(["Explains productivity gains", "解释生产率提升"]), weaknesses: LS(["Effects vary by context", "效应因情境而异"]) },
    { name: L("Behavioural Economics", "行为经济学"), match: 72, diagram: "supplyDemand", explanation: L("Present bias leads riders to under-insure voluntarily, supporting a mandate.", "现时偏好使骑手自愿投保不足，支持强制规定。"), relevance: L("Counters the 'let riders choose' objection.", "回应“让骑手自选”的反对意见。"), strengths: LS(["Realistic micro-foundations", "贴近现实的微观基础"]), weaknesses: LS(["Paternalism concerns", "存在家长式担忧"]) },
  ],
  counter: [
    { a: L("Worker Protection", "劳动者保护"), b: L("Labour-Market Flexibility", "劳动力市场灵活性"), tension: L("Does mandated security improve welfare, or destroy the low-barrier flexibility riders rely on?", "强制保障是提升福利，还是摧毁骑手所依赖的低门槛灵活性？") },
    { a: L("Mandate (Pigouvian)", "强制（庇古式）"), b: L("Free Choice", "自由选择"), tension: L("Should the state internalise the externality, or trust riders to insure themselves?", "国家应内部化外部性，还是信任骑手自行投保？") },
  ],
  methods: [
    { name: L("Monopsony Wage Regression", "买方垄断工资回归"), fit: 90, purpose: L("Estimate platform wage-setting power and labour-supply elasticity.", "估计平台的工资设定权与劳动供给弹性。"), formula: "ln(w) = β₀ + β₁ ln(L_supply elasticity) + controls + ε", assumptions: L("Identifiable supply elasticity; exogenous variation.", "可识别的供给弹性；外生变动。"), data: L("Rider pay, hours, local labour-market panels.", "骑手薪酬、工时、地方劳动力市场面板。"), advantages: L("Reveals whether platforms have wage power.", "揭示平台是否具备工资势力。"), weaknesses: L("Endogeneity of effort and hours.", "努力与工时的内生性。") },
    { name: L("Difference-in-Differences (pilot regions)", "双重差分（试点地区）"), fit: 92, purpose: L("Compare employment & pay where pilots applied vs not.", "对比适用与未适用试点地区的就业与薪酬。"), formula: "Y = β₀ + β₁Treat + β₂Post + β₃(Treat·Post) + ε", assumptions: L("Parallel trends across regions.", "各地区趋势平行。"), data: L("Regional rider counts, earnings, fees.", "地区骑手数、收入、费用。"), advantages: L("Credible causal incidence estimate.", "可信的因果归宿估计。"), weaknesses: L("Pilot selection may be non-random.", "试点选取可能非随机。") },
    { name: L("Tax-Incidence / Pass-Through Model", "税收归宿／转嫁模型"), fit: 88, purpose: L("Allocate the mandate's cost across platforms, riders and consumers.", "在平台、骑手与消费者间分配强制规定的成本。"), formula: "Burden_consumers = εS / (εS + εD)", assumptions: L("Known supply & demand elasticities.", "已知供给与需求弹性。"), data: L("Fee, wage and order-volume responses.", "费用、薪酬与订单量的反应。"), advantages: L("Directly answers 'who pays'.", "直接回答“谁来付”。"), weaknesses: L("Elasticities context-specific.", "弹性依赖具体情境。") },
    { name: L("Agent-Based Simulation", "基于主体的模拟"), fit: 70, purpose: L("Simulate rider supply and platform responses to the mandate.", "模拟骑手供给与平台对强制规定的反应。"), formula: "macro = Σ behaviour(riderᵢ | pay rules, outside option)", assumptions: L("Specified behavioural rules.", "设定的行为规则。"), data: L("Micro pay, acceptance and exit parameters.", "微观薪酬、接单与退出参数。"), advantages: L("Captures heterogeneity & dynamics.", "刻画异质性与动态。"), weaknesses: L("Hard to calibrate.", "难以校准。") },
  ],
  datasets: [
    { name: "ILO Statistics (informal employment)", provider: "ILO", url: "https://ilostat.ilo.org" },
    { name: "OECD Employment Database", provider: "OECD", url: "https://www.oecd.org/employment/" },
    { name: "World Bank Jobs & Social Protection", provider: "World Bank", url: "https://www.worldbank.org/en/topic/socialprotection" },
    { name: "National Bureau of Statistics", provider: "NBS China", url: "https://www.stats.gov.cn/english/" },
  ],
  evidence: [
    {
      title: L("ILO data on informal & platform work", "ILO 非正规与平台用工数据"),
      publisher: "ILO", grade: "A+", reliability: 94, bias: L("Low · labour-standards perspective", "低 · 劳工标准视角"),
      requiredData: L("Share of informal workers, coverage rates, hours.", "非正规劳动者占比、覆盖率、工时。"),
      whyItMatters: L("Sizes the uninsured population the policy targets.", "测算政策所针对的无保险人群规模。"),
      howItSupports: L("Provides the base for incidence and coverage modelling.", "为归宿与覆盖建模提供基础。"),
      url: "https://ilostat.ilo.org", year: 2026,
    },
    {
      title: L("Peer-reviewed monopsony-in-labour studies", "同行评审的劳动市场买方垄断研究"),
      publisher: "Quarterly Journal of Economics", grade: "A", reliability: 90, bias: L("Low · academic", "低 · 学术"),
      requiredData: L("Labour-supply elasticity estimates to the firm.", "对企业的劳动供给弹性估计。"),
      whyItMatters: L("If elasticity is low, platforms — not workers — absorb the cost.", "若弹性较低，则平台而非劳动者承担成本。"),
      howItSupports: L("Calibrates the wage-power and incidence models.", "校准工资势力与归宿模型。"),
      url: "https://academic.oup.com/qje", year: 2022,
    },
    {
      title: L("Pilot-program evaluation reports", "试点项目评估报告"),
      publisher: "Government research institute", grade: "B", reliability: 72, bias: L("Moderate · official sponsor", "中等 · 官方主办"),
      requiredData: L("Pre/post employment, earnings, compliance in pilots.", "试点前后就业、收入、合规。"),
      whyItMatters: L("Direct evidence on real-world responses to mandates.", "关于现实中对强制规定反应的直接证据。"),
      howItSupports: L("Anchors the DiD treatment effect.", "支撑双重差分处理效应。"),
      url: "https://www.worldbank.org/en/topic/socialprotection", year: 2025,
    },
    {
      title: L("Platform transparency / investigative reporting", "平台透明度与调查报道"),
      publisher: "Caixin / academic exposés", grade: "C", reliability: 60, bias: L("Editorial; vivid but selective", "编辑取向；生动但具选择性"),
      requiredData: L("Algorithmic pay rules, dispatch logic, injury cases.", "算法薪酬规则、派单逻辑、工伤案例。"),
      whyItMatters: L("Documents the asymmetry and safety incentives qualitatively.", "定性记录信息不对称与安全激励。"),
      howItSupports: L("Motivates the principal-agent framing; not for magnitudes.", "支撑委托代理框架；不作量级来源。"),
      url: "https://www.caixinglobal.com", year: 2026,
    },
  ],
  literature: {
    supporting: [
      { cite: "Card & Krueger lineage (minimum-wage)", finding: L("Mandated pay floors need not cut employment under monopsony.", "在买方垄断下，强制工资下限未必减少就业。"), stance: "support" },
      { cite: "Dube, Manning & Naidu (monopsony)", finding: L("Labour-supply elasticity to platforms is low, implying limited job loss.", "对平台的劳动供给弹性较低，意味着就业损失有限。"), stance: "support" },
    ],
    opposing: [
      { cite: "Competitive labour-demand view", finding: L("Higher mandated costs reduce hours and headcount.", "更高的强制成本会减少工时与用工人数。"), stance: "oppose" },
      { cite: "Flexibility-premium scholarship", finding: L("Workers value flexibility highly; formalisation can lower welfare.", "劳动者高度重视灵活性；正规化可能降低福利。"), stance: "oppose" },
    ],
    debates: LS(
      ["Monopsony vs competitive labour market — does the mandate cut jobs?", "买方垄断 对 竞争性劳动市场——强制规定是否减少就业？"],
      ["Is gig flexibility a true preference or a constrained outside option?", "零工灵活性是真实偏好还是受约束的外部选项？"],
    ),
    authors: [
      { name: "Alan Manning", field: L("Monopsony & labour", "买方垄断与劳动") },
      { name: "Arindrajit Dube", field: L("Minimum wage & employment", "最低工资与就业") },
      { name: "David Weil", field: L("Fissured workplace", "碎裂化的工作场所") },
    ],
    gaps: LS(["Few causal estimates for platform social-insurance mandates.", "针对平台社保强制的因果估计稀少。"], ["Long-run effects on platform business models unknown.", "对平台商业模式的长期影响未知。"]),
    future: LS(["DiD using staggered pilot rollouts.", "利用错位试点推广做双重差分。"], ["Estimate labour-supply elasticity to platforms.", "估计对平台的劳动供给弹性。"]),
    consensus: 64,
  },
  proposals: [
    {
      id: "A", name: L("Mandatory platform contributions (full coverage)", "强制平台缴费（全覆盖）"),
      objective: L("Require platforms to fund pension and injury insurance for all active riders.", "要求平台为所有在岗骑手缴纳养老金与工伤保险。"),
      cost: 4, impact: 5, fairness: 5, feasibility: 3, risk: 3,
      steps: LS(["Define contribution rates and eligibility.", "确定缴费率与资格。"], ["Build payroll integration with platforms.", "与平台搭建社保扣缴对接。"], ["Audit compliance; penalise evasion.", "审计合规；惩罚规避。"]),
      timeline: L("12–24 months to full rollout.", "12–24 个月全面推行。"),
      budget: L("Borne by platforms; possible state co-funding for transition.", "由平台承担；过渡期或由国家共同出资。"),
      stakeholderResponses: [{ who: L("Platforms", "平台"), reaction: L("Resist; warn of fee rises or fewer riders.", "抵制；警告将涨费或减少骑手。") }, { who: L("Riders", "骑手"), reaction: L("Gain security; fear lower take-home pay.", "获得保障；担心到手收入下降。") }],
      risks: LS(["Cost pass-through to riders/consumers.", "成本转嫁给骑手／消费者。"], ["Evasion via reclassification.", "通过重新归类规避。"]),
      alternatives: LS(["Portable benefits fund (Proposal B).", "可携带福利基金（方案 B）。"]),
      metrics: LS(["Coverage rate; injury-related public costs.", "覆盖率；工伤相关公共成本。"], ["Change in rider earnings & headcount.", "骑手收入与人数变化。"]),
    },
    {
      id: "B", name: L("Portable benefits fund (pro-rata per order)", "可携带福利基金（按单分摊）"),
      objective: L("Attach small per-order contributions to a portable account, preserving flexibility.", "为每单附加小额缴费进入可携带账户，保留灵活性。"),
      cost: 3, impact: 4, fairness: 4, feasibility: 4, risk: 2,
      steps: LS(["Levy a per-delivery contribution across platforms.", "在各平台对每单征收缴费。"], ["Pool into individual portable accounts.", "汇入个人可携带账户。"], ["Allow multi-platform accrual.", "允许多平台累积。"]),
      timeline: L("9–18 months.", "9–18 个月。"),
      budget: L("Funded by a transparent per-order levy.", "由透明的按单征费提供资金。"),
      stakeholderResponses: [{ who: L("Riders", "骑手"), reaction: L("Keep flexibility plus some security.", "保留灵活性并获得部分保障。") }, { who: L("Platforms", "平台"), reaction: L("Prefer to full employment status.", "相较完全雇佣身份更可接受。") }],
      risks: LS(["Contributions may be too small to matter.", "缴费可能过小而效果有限。"]),
      alternatives: LS(["Full contributions (Proposal A).", "全额缴费（方案 A）。"]),
      metrics: LS(["Account balances; coverage continuity.", "账户余额；覆盖连续性。"]),
    },
    {
      id: "C", name: L("Reclassify riders as employees", "将骑手重新归类为雇员"),
      objective: L("Grant full employment rights and benefits via legal reclassification.", "通过法律重新归类授予完整雇佣权利与福利。"),
      cost: 5, impact: 5, fairness: 5, feasibility: 2, risk: 4,
      steps: LS(["Legislate employee status for controlled work.", "为受控用工立法确立雇员身份。"], ["Mandate full benefits and protections.", "强制完整福利与保护。"]),
      timeline: L("2–4 years incl. legal challenges.", "含法律挑战 2–4 年。"),
      budget: L("Large cost on platforms; restructuring likely.", "对平台成本巨大；很可能重组。"),
      stakeholderResponses: [{ who: L("Platforms", "平台"), reaction: L("May cut rider numbers or scheduling flexibility.", "可能削减骑手数量或排班灵活性。") }, { who: L("Some riders", "部分骑手"), reaction: L("Lose flexibility they value.", "失去其看重的灵活性。") }],
      risks: LS(["Significant job losses; reduced flexibility.", "显著就业损失；灵活性下降。"]),
      alternatives: LS(["Portable benefits (Proposal B).", "可携带福利（方案 B）。"]),
      metrics: LS(["Employment level; formal-coverage rate.", "就业水平；正式覆盖率。"]),
    },
  ],
  critical: [
    { key: "ce.shortRun", text: L("Labour costs rise; platforms adjust fees, pay or rider numbers as coverage begins.", "用工成本上升；覆盖开始时平台调整费用、薪酬或骑手数量。") },
    { key: "ce.longRun", text: L("Business models may restructure toward scheduled work or higher prices, settling at a new equilibrium.", "商业模式或转向排班用工或更高价格，趋于新的均衡。") },
    { key: "ce.intended", text: L("Provide riders with pension and injury security and internalise injury externalities.", "为骑手提供养老与工伤保障，并内部化工伤外部性。") },
    { key: "ce.unintended", text: L("Possible pass-through to riders/consumers, reclassification, or reduced hiring.", "可能向骑手／消费者转嫁、重新归类或减少招募。") },
    { key: "ce.equity", text: L("Improves security for vulnerable workers but may reduce easy-entry opportunities.", "提升弱势劳动者保障，却可能减少便捷进入的机会。") },
    { key: "ce.sustainability", text: L("More sustainable social protection if financing is stable and evasion controlled.", "若融资稳定且规避受控，社会保护更可持续。") },
    { key: "ce.ethical", text: L("Balances dignity and security against autonomy and flexibility.", "在尊严与保障 对 自主与灵活之间权衡。") },
    { key: "ce.alternatives", text: L("Portable benefits offer a middle path between mandates and the status quo.", "可携带福利在强制与现状之间提供折中路径。") },
  ],
  essay: {
    basic: {
      rq: L("Should food-delivery platforms be required to provide insurance for riders?", "外卖平台是否应被要求为骑手提供保险？"),
      thesis: L("Requiring insurance protects riders from injury and old-age risk, but it may raise costs, so platforms and consumers might pay more.", "要求提供保险保护骑手免受工伤与养老风险，但可能抬高成本，平台与消费者或需多付。"),
      outline: [
        { heading: L("Introduction", "引言"), points: LS(["Explain gig work and the question.", "解释零工与问题。"]) },
        { heading: L("Point — protects riders", "论点——保护骑手"), points: LS(["Insurance reduces injury and pension risk.", "保险降低工伤与养老风险。"]) },
        { heading: L("Point — raises costs", "论点——抬高成本"), points: LS(["Higher costs may mean higher delivery fees (labour demand & supply).", "更高成本或意味更高配送费（劳动供需）。"]) },
        { heading: L("Conclusion", "结论"), points: LS(["Give a simple, balanced judgement.", "给出简单而平衡的判断。"]) },
      ],
      note: L("Two-sided structure, one labour-market diagram, clear definitions.", "两面结构、一张劳动市场图、清晰定义。"),
    },
    advanced: {
      rq: L("To what extent will mandating social-insurance contributions improve the welfare of delivery riders?", "强制缴纳社会保险在多大程度上会提升外卖骑手的福利？"),
      thesis: L("Because the platform labour market is monopsonistic, the mandate may raise rider welfare with limited job loss; but pass-through and reclassification mean the net effect is an empirical question.", "由于平台劳动市场具买方垄断性，强制规定可能在就业损失有限的情况下提升骑手福利；但转嫁与重新归类意味着净效应是实证问题。"),
      outline: [
        { heading: L("Introduction", "引言"), points: LS(["Define gig work; set up incidence framework.", "界定零工；搭建归宿框架。"]) },
        { heading: L("Argument 1 — monopsony & employment", "论点一——买方垄断与就业"), points: LS(["Monopsony labour diagram.", "买方垄断劳动图。"], ["Evidence: low supply elasticity.", "证据：低供给弹性。"], ["Counter: competitive view predicts job loss.", "反驳：竞争视角预测就业损失。"], ["Evaluate via elasticity.", "以弹性评估。"]) },
        { heading: L("Argument 2 — externalities & principal-agent", "论点二——外部性与委托代理"), points: LS(["Internalising injury costs; safer incentives.", "内部化工伤成本；更安全的激励。"], ["Counter: rules reduce flexibility.", "反驳：规则降低灵活性。"]) },
        { heading: L("Argument 3 — incidence", "论点三——归宿"), points: LS(["Who pays: platforms, riders or consumers?", "谁来付：平台、骑手还是消费者？"]) },
        { heading: L("Conclusion", "结论"), points: LS(["Conditional judgement on elasticities & enforcement.", "基于弹性与执行的有条件判断。"]) },
      ],
      note: L("Three argument blocks with diagrams, evidence, counters and evaluation.", "三段论证，含图、证据、反驳与评估。"),
    },
    research: {
      rq: L("What is the incidence and welfare effect of mandating platform social-insurance contributions for gig delivery riders?", "强制平台为零工骑手缴纳社会保险的归宿与福利效应如何？"),
      thesis: L("Combining monopsony wage estimates with a pass-through model and pilot-based DiD, the mandate plausibly raises rider welfare net of modest pass-through under low supply elasticity; a portable-benefits design weakly dominates full reclassification on feasibility and flexibility.", "结合买方垄断工资估计、转嫁模型与基于试点的双重差分，在低供给弹性下，扣除有限转嫁后该强制规定很可能提升骑手净福利；在可行性与灵活性上，可携带福利设计对完全重新归类呈弱占优。"),
      outline: [
        { heading: L("Introduction & contribution", "引言与贡献"), points: LS(["Frame the gig-protection debate and the gap.", "界定零工保护之辩与空白。"]) },
        { heading: L("Literature review", "文献综述"), points: LS(["Monopsony, fissured work, minimum-wage incidence.", "买方垄断、碎裂化工作、最低工资归宿。"]) },
        { heading: L("Theoretical framework", "理论框架"), points: LS(["Monopsony + externality + principal-agent model.", "买方垄断 + 外部性 + 委托代理模型。"]) },
        { heading: L("Methodology", "方法"), points: LS(["Pilot DiD; supply-elasticity estimation; pass-through.", "试点双重差分；供给弹性估计；转嫁。"]) },
        { heading: L("Results & policy evaluation", "结果与政策评估"), points: LS(["Compare mandate, portable benefits, reclassification.", "比较强制、可携带福利、重新归类。"]) },
        { heading: L("Limitations & research gaps", "局限与研究空白"), points: LS(["Pilot selection; long-run model effects.", "试点选取；长期模式效应。"]) },
      ],
      note: L("Academic structure with literature integration, identification strategy and policy evaluation.", "学术结构，含文献整合、识别策略与政策评估。"),
    },
  },
};
