import { L, LS, type CaseProposal } from "./types";

/** Six policy proposals, each with embedded evaluation (replaces standalone critical section). */
export const deliveryProposals: CaseProposal[] = [
  {
    id: "A", name: L("Mandatory per-order occupational-injury insurance", "强制按单工伤保险"),
    objective: L("Require platforms to fund work-injury insurance for every active rider, per order — the current pilot, scaled nationwide.", "要求平台按单为每位在岗骑手缴纳工伤保险——即当前试点的全国扩面。"),
    mechanism: L("A small per-order levy auto-enrols riders; no employee reclassification needed.", "小额按单征费自动为骑手参保；无需重新归类为雇员。"),
    steps: LS(["Set the per-order rate by industry.", "按行业设定按单费率。"], ["Integrate enrolment into platform dispatch systems.", "将参保接入平台派单系统。"], ["Audit compliance; publish coverage data.", "审计合规；公开覆盖数据。"]),
    timeline: L("Already piloted since 2022; nationwide rollout 2026.", "2022 年起已试点；2026 年全国推开。"),
    budget: L("Funded by per-order contributions; low admin cost via platforms.", "由按单缴费提供资金；经平台代办行政成本低。"),
    benefits: LS(["Covers the most urgent risk (injury) fast.", "快速覆盖最紧迫的风险（工伤）。"], ["Already proven to scale (12.3m enrolled).", "已证明可扩展（参保 1,234 万）。"]),
    stakeholdersList: LS(["Riders", "骑手"], ["Platforms", "平台"], ["MOHRSS", "人社部"]),
    cost: 2, impact: 4, fairness: 4, feasibility: 5, risk: 2,
    stakeholderResponses: [{ who: L("Platforms", "平台"), reaction: L("Accept as cheaper than employee status.", "接受，因比雇员身份更便宜。") }, { who: L("Riders", "骑手"), reaction: L("Welcome injury cover; want pay protected.", "欢迎工伤保障；希望收入不受损。") }],
    risks: LS(["Covers only injury, not pension/medical.", "仅覆盖工伤，不含养老／医疗。"]),
    alternatives: LS(["Full social insurance (Proposal C).", "完整社保（方案 C）。"]),
    metrics: LS(["Coverage rate; claims paid; injury-cost burden on public hospitals.", "覆盖率；理赔兑付；公立医院工伤成本负担。"]),
    evalProblems: LS(["Leaves the larger pension and medical gaps unaddressed.", "未触及更大的养老与医疗缺口。"]),
    evalUnintended: LS(["Platforms may reclassify or cap hours to limit per-order cost.", "平台可能重新归类或限制工时以压低按单成本。"]),
    evalPolitical: LS(["Low conflict — already endorsed by nine ministries.", "冲突低——已获九部门支持。"]),
    evalTradeoffs: LS(["Cheap and feasible, but partial protection.", "便宜且可行，但保护不完整。"]),
    evalLongRisks: LS(["May entrench injury-only cover as 'good enough', delaying fuller reform.", "可能将“仅工伤”固化为“够用”，延缓更全面改革。"]),
  },
  {
    id: "B", name: L("Portable benefits account (per-order, multi-platform)", "可携带福利账户（按单、跨平台）"),
    objective: L("Attach contributions to a portable individual account riders keep across platforms and cities.", "将缴费挂入骑手在平台与城市间可携带的个人账户。"),
    mechanism: L("Every order on any platform pays into the rider's account, funding pension + injury + medical.", "任一平台的每单都向骑手账户缴费，为养老＋工伤＋医疗提供资金。"),
    steps: LS(["Create individual portable accounts.", "建立个人可携带账户。"], ["Require all platforms to contribute per order.", "要求所有平台按单缴费。"], ["Allow accrual across jobs and regions.", "允许跨工作与地区累积。"]),
    timeline: L("9–18 months to build account infrastructure.", "9–18 个月建设账户基础设施。"),
    budget: L("Funded by a transparent per-order levy across platforms.", "由跨平台透明的按单征费提供资金。"),
    benefits: LS(["Preserves flexibility while extending broad cover.", "在扩大覆盖的同时保留灵活性。"], ["Fits multi-homing riders who switch platforms.", "契合在多平台间切换的骑手。"]),
    stakeholdersList: LS(["Riders", "骑手"], ["Platforms", "平台"], ["Social-security funds", "社保基金"]),
    cost: 3, impact: 5, fairness: 5, feasibility: 3, risk: 3,
    stakeholderResponses: [{ who: L("Riders", "骑手"), reaction: L("Keep flexibility plus broad security.", "保留灵活性并获得广泛保障。") }, { who: L("Platforms", "平台"), reaction: L("Prefer to full employee status.", "相较完全雇员身份更可接受。") }],
    risks: LS(["Requires cross-platform coordination and data-sharing.", "需要跨平台协调与数据共享。"]),
    alternatives: LS(["Single-platform contributions (Proposal A).", "单平台缴费（方案 A）。"]),
    metrics: LS(["Account balances; portability take-up; coverage continuity.", "账户余额；可携带使用率；覆盖连续性。"]),
    evalProblems: LS(["Coordinating competing platforms is hard.", "协调相互竞争的平台困难。"]),
    evalUnintended: LS(["Contribution rates set too low could under-fund pensions.", "费率设置过低可能使养老金资金不足。"]),
    evalPolitical: LS(["Platforms resist sharing rider data with rivals.", "平台抵触与对手共享骑手数据。"]),
    evalTradeoffs: LS(["Best protection-flexibility balance, but harder to build.", "保护与灵活性的最佳平衡，但建设更难。"]),
    evalLongRisks: LS(["Fragmented systems could leave gaps at job transitions.", "系统碎片化可能在工作转换处留下缺口。"]),
  },
  {
    id: "C", name: L("Reclassify riders as employees", "将骑手重新归类为雇员"),
    objective: L("Grant full employee status and the complete social-insurance package.", "授予完整雇员身份与全套社会保险。"),
    mechanism: L("Legal reclassification triggers mandatory pension, medical, injury, unemployment cover.", "法律重新归类触发强制养老、医疗、工伤、失业覆盖。"),
    steps: LS(["Legislate employee status for controlled platform work.", "为受控平台用工立法确立雇员身份。"], ["Mandate the full benefit package.", "强制全套福利。"]),
    timeline: L("2–4 years including legal challenges.", "含法律挑战 2–4 年。"),
    budget: L("Large cost on platforms; likely business-model restructuring.", "对平台成本巨大；很可能重组商业模式。"),
    benefits: LS(["Maximal, complete protection.", "最大化、完整的保护。"], ["Ends the classification grey zone.", "终结身份灰色地带。"]),
    stakeholdersList: LS(["Riders", "骑手"], ["Platforms", "平台"], ["Courts", "法院"]),
    cost: 5, impact: 5, fairness: 5, feasibility: 2, risk: 4,
    stakeholderResponses: [{ who: L("Platforms", "平台"), reaction: L("Strongly resist; may cut rider numbers.", "强烈抵制；可能削减骑手数量。") }, { who: L("Some riders", "部分骑手"), reaction: L("Fear lost flexibility and casual entry.", "担心失去灵活性与临时进入。") }],
    risks: LS(["Significant job losses; reduced flexibility.", "显著就业损失；灵活性下降。"]),
    alternatives: LS(["Portable benefits (Proposal B).", "可携带福利（方案 B）。"]),
    metrics: LS(["Employment level; formal-coverage rate; rider income.", "就业水平；正式覆盖率；骑手收入。"]),
    evalProblems: LS(["Chen et al. (2019) imply large flexibility surplus would be destroyed.", "Chen 等（2019）暗示将摧毁巨大的灵活性剩余。"]),
    evalUnintended: LS(["Platforms shift to scheduled shifts or fewer riders.", "平台转向排班或减少骑手。"]),
    evalPolitical: LS(["High conflict; platforms and some riders both resist.", "冲突高；平台与部分骑手均抵制。"]),
    evalTradeoffs: LS(["Maximal protection at the cost of flexibility and jobs.", "以灵活性与就业为代价换取最大保护。"]),
    evalLongRisks: LS(["Could shrink the sector that absorbs low-skilled urban employment.", "可能收缩吸纳低技能城市就业的部门。"]),
  },
  {
    id: "D", name: L("Government co-financed subsidy (shared contribution)", "政府共担补贴（共同缴费）"),
    objective: L("Split social-insurance contributions between platforms, riders and the state to ease the cost burden.", "在平台、骑手与国家之间分摊社保缴费以减轻成本负担。"),
    mechanism: L("Public subsidy lowers the per-order cost, raising take-up without crushing margins.", "公共补贴降低按单成本，在不压垮利润率的情况下提升参保。"),
    steps: LS(["Set a three-way contribution split.", "设定三方缴费比例。"], ["Target subsidies at low-income riders.", "向低收入骑手定向补贴。"], ["Sunset the subsidy as coverage matures.", "随覆盖成熟逐步退出补贴。"]),
    timeline: L("1–2 years; tied to fiscal budgeting.", "1–2 年；与财政预算挂钩。"),
    budget: L("Significant public outlay; on-budget and visible.", "较大公共支出；列入预算且可见。"),
    benefits: LS(["Eases pass-through to riders and consumers.", "缓解向骑手与消费者的转嫁。"], ["Boosts take-up among low earners.", "提升低收入者参保。"]),
    stakeholdersList: LS(["Riders", "骑手"], ["Platforms", "平台"], ["Taxpayers", "纳税人"]),
    cost: 4, impact: 4, fairness: 4, feasibility: 3, risk: 3,
    stakeholderResponses: [{ who: L("Riders", "骑手"), reaction: L("Welcome lower personal cost.", "欢迎更低的个人成本。") }, { who: L("Taxpayers", "纳税人"), reaction: L("Question subsidising profitable platforms.", "质疑补贴盈利平台。") }],
    risks: LS(["Fiscal cost; risk of subsidising platform profits.", "财政成本；补贴平台利润的风险。"]),
    alternatives: LS(["Pure platform funding (Proposal A/B).", "纯平台出资（方案 A/B）。"]),
    metrics: LS(["Take-up among low earners; fiscal cost per rider covered.", "低收入者参保率；每覆盖一名骑手的财政成本。"]),
    evalProblems: LS(["Public money may subsidise highly profitable firms.", "公共资金可能补贴高盈利企业。"]),
    evalUnintended: LS(["Platforms may not pass the subsidy through to riders.", "平台可能不将补贴转嫁给骑手。"]),
    evalPolitical: LS(["Competes with other social-spending priorities.", "与其他社会支出优先项竞争。"]),
    evalTradeoffs: LS(["Smooths incidence but uses scarce fiscal capacity.", "平滑归宿，但占用稀缺财政能力。"]),
    evalLongRisks: LS(["Subsidy may become hard to withdraw politically.", "补贴可能在政治上难以退出。"]),
  },
  {
    id: "E", name: L("Algorithmic transparency & safety standards", "算法透明与安全标准"),
    objective: L("Regulate dispatch algorithms and delivery-time pressure to cut the accidents that drive injury costs.", "监管派单算法与配送时限压力，以减少推高工伤成本的事故。"),
    mechanism: L("Mandate published pay/penalty rules, minimum delivery times and rest requirements.", "强制公开薪酬／处罚规则、最低配送时限与休息要求。"),
    steps: LS(["Require algorithm disclosure to regulators.", "要求向监管者披露算法。"], ["Set safe minimum delivery times.", "设定安全的最低配送时限。"], ["Penalise unsafe incentive design.", "惩罚不安全的激励设计。"]),
    timeline: L("1–2 years; build on Shanghai's safety-code model.", "1–2 年；借鉴上海安全码模式。"),
    budget: L("Mainly regulatory/monitoring cost.", "主要为监管／监测成本。"),
    benefits: LS(["Attacks the root cause of injuries, reducing claims.", "针对工伤根因，减少理赔。"], ["Shanghai shows it works (−42.9% deaths).", "上海证明有效（致死 −42.9%）。"]),
    stakeholdersList: LS(["Riders", "骑手"], ["Platforms", "平台"], ["Road users", "道路使用者"]),
    cost: 2, impact: 3, fairness: 4, feasibility: 3, risk: 2,
    stakeholderResponses: [{ who: L("Platforms", "平台"), reaction: L("Resist disclosing proprietary algorithms.", "抵触披露专有算法。") }, { who: L("Public", "公众"), reaction: L("Support safer streets.", "支持更安全的街道。") }],
    risks: LS(["Platforms may game disclosed rules.", "平台可能操弄已披露的规则。"]),
    alternatives: LS(["Insurance-only approach (Proposal A).", "仅保险方案（方案 A）。"]),
    metrics: LS(["Accident and violation rates; on-time-pressure complaints.", "事故与违法率；准时压力投诉。"]),
    evalProblems: LS(["Hard to verify algorithm compliance.", "难以核验算法合规。"]),
    evalUnintended: LS(["Longer delivery times may cut order volume and rider pay.", "更长配送时限可能减少订单量与骑手收入。"]),
    evalPolitical: LS(["Platforms lobby hard against disclosure.", "平台强力游说反对披露。"]),
    evalTradeoffs: LS(["Prevention is cheap but politically contested.", "预防成本低，但政治上有争议。"]),
    evalLongRisks: LS(["Regulation may lag fast-changing algorithms.", "监管可能落后于快速变化的算法。"]),
  },
  {
    id: "F", name: L("Sectoral collective bargaining", "行业集体协商"),
    objective: L("Let rider representatives (via the ACFTU) bargain pay and benefits sector-wide.", "让骑手代表（经全国总工会）在全行业协商薪酬与福利。"),
    mechanism: L("Negotiated minimum standards bind all platforms, countering monopsony power.", "协商出的最低标准约束所有平台，对冲买方垄断势力。"),
    steps: LS(["Recognise rider bargaining units.", "认可骑手协商单位。"], ["Negotiate sector-wide minimum terms.", "协商全行业最低条款。"], ["Enforce agreements across platforms.", "在各平台执行协议。"]),
    timeline: L("2–3 years to build bargaining institutions.", "2–3 年建立协商机制。"),
    budget: L("Low direct fiscal cost; outcomes set by negotiation.", "直接财政成本低；结果由协商决定。"),
    benefits: LS(["Directly offsets platform wage-setting power.", "直接对冲平台工资设定权。"], ["Adapts terms to local conditions.", "使条款适应地方情况。"]),
    stakeholdersList: LS(["Riders", "骑手"], ["ACFTU", "全国总工会"], ["Platforms", "平台"]),
    cost: 2, impact: 4, fairness: 5, feasibility: 2, risk: 3,
    stakeholderResponses: [{ who: L("Unions", "工会"), reaction: L("Gain reach into a huge workforce.", "获得对庞大劳动群体的触达。") }, { who: L("Platforms", "平台"), reaction: L("Resist binding sector-wide terms.", "抵制约束性的全行业条款。") }],
    risks: LS(["Dispersed riders are hard to organise.", "分散的骑手难以组织。"]),
    alternatives: LS(["State-set standards (Proposal A/C).", "国家设定标准（方案 A/C）。"]),
    metrics: LS(["Coverage of agreements; negotiated wage floor; membership.", "协议覆盖面；协商工资下限；会员数。"]),
    evalProblems: LS(["Low bargaining power where riders are atomised.", "骑手原子化处议价力低。"]),
    evalUnintended: LS(["Sector deals may exclude casual riders.", "行业协议可能排斥临时骑手。"]),
    evalPolitical: LS(["Bargaining scope is tightly framed within the state system.", "协商范围在国家体系内被严格限定。"]),
    evalTradeoffs: LS(["Durable if it works, but institution-building is slow.", "若奏效则持久，但机制建设缓慢。"]),
    evalLongRisks: LS(["May stall without genuine independent representation.", "若无真正独立代表可能停滞。"]),
  },
];
