import { L, type CaseTimelineNode, type CaseStakeholder, type CaseRelation } from "./types";

export const deliveryTimeline: CaseTimelineNode[] = [
  {
    date: "2015–2018", kind: "cause",
    title: L("App-based delivery scales on the contractor model", "基于 App 的外卖以承包人模式扩张"),
    detail: L("Meituan and Ele.me build a mass on-demand workforce.", "美团与饿了么建立大规模即时配送劳动力。"),
    what: L("Smartphone penetration and venture funding let Meituan and Ele.me grow food delivery into a nationwide, on-demand service staffed by millions of riders engaged as independent contractors.", "智能手机普及与风险资本使美团、饿了么将外卖发展为遍及全国的即时服务，由数百万以独立承包人身份签约的骑手提供。"),
    why: L("Contractor classification kept labour costs low and let supply scale instantly with demand — the model's core economic logic.", "承包人身份压低用工成本，并使供给随需求即时扩张——这是该模式的核心经济逻辑。"),
    who: L("Platforms, venture investors, and a fast-growing pool of mostly migrant riders.", "平台、风险投资者，以及快速增长、以流动人口为主的骑手群体。"),
    influence: L("Locked in a structure where riders were outside the employment-based social-insurance system from the start.", "锁定了一种结构：骑手从一开始就被置于以雇佣为基础的社保体系之外。"),
    importance: L("This is the root cause: the coverage gap is a by-product of the model that made delivery cheap and ubiquitous.", "这是根源：覆盖缺口是使外卖廉价且无处不在的模式的副产品。"),
  },
  {
    date: "2020–2021", kind: "trigger",
    title: L("'Trapped in the system' sparks public and regulatory attention", "“困在系统里”引发公众与监管关注"),
    detail: L("Viral reporting on algorithmic pressure and rider safety.", "关于算法压力与骑手安全的爆款报道。"),
    what: L("A widely shared exposé on how dispatch algorithms squeeze delivery times turned rider conditions into a national conversation, followed by multi-ministry guidance in 2021 on protecting 'new employment forms' workers.", "一篇广为传播的深度报道揭示派单算法如何压缩配送时间，使骑手处境成为全国话题；随后 2021 年多部门出台保护“新就业形态”劳动者的指导意见。"),
    why: L("Public pressure plus visible safety incidents made inaction politically costly.", "公众压力叠加显性安全事故，使不作为在政治上代价高昂。"),
    who: L("Media, the public, MOHRSS and eight other ministries, the platforms.", "媒体、公众、人社部及其他八个部门、各平台。"),
    influence: L("Created the 'new employment forms' (新就业形态) category that later reforms build on.", "创设了后续改革所依托的“新就业形态”类别。"),
    importance: L("The turning point from problem-awareness to a concrete regulatory category.", "从问题意识转向具体监管类别的转折点。"),
  },
  {
    date: "Jul 2022", kind: "milestone",
    title: L("Occupational-injury insurance pilot launches in 7 provinces", "职业伤害保障试点在 7 省启动"),
    detail: L("First benefit decoupled from full employee status.", "首个与完整雇员身份脱钩的待遇。"),
    what: L("MOHRSS launched a work-injury insurance pilot across Beijing, Shanghai, Jiangsu, Guangdong, Hainan, Chongqing and Zhejiang, covering seven platforms including Meituan, Ele.me and Didi.", "人社部在北京、上海、江苏、广东、海南、重庆、浙江启动工伤保险试点，覆盖美团、饿了么、滴滴等七个平台。"),
    why: L("Injury risk was the most urgent, measurable and politically uncontroversial gap to close first.", "工伤风险是最紧迫、可测量且政治上最无争议、可优先弥合的缺口。"),
    who: L("MOHRSS, seven pilot platforms, riders in four industries (ride-hail, food delivery, instant delivery, same-city freight).", "人社部、七个试点平台、四个行业（网约车、外卖、即时配送、同城货运）的骑手。"),
    influence: L("Proved a per-order, platform-funded contribution could work without reclassifying riders as employees.", "证明按单、由平台出资的缴费可在不将骑手重新归类为雇员的情况下运作。"),
    importance: L("The template the 2025 national expansion scales up.", "2025 年全国扩面所放大的范本。"),
  },
  {
    date: "Oct 2023", kind: "milestone",
    title: L("Pilot enrolment reaches ~6.68 million", "试点参保达约 668 万"),
    detail: L("Rapid uptake validates the per-order funding model.", "快速参保验证了按单出资模式。"),
    what: L("Within about 15 months the injury-insurance pilot had enrolled roughly 6.68 million workers across the four industries and seven platforms.", "约 15 个月内，工伤保险试点已在四个行业、七个平台参保约 668 万人。"),
    why: L("Because platforms enrolled riders automatically per order, take-up did not depend on individual voluntary sign-up.", "因平台按单自动为骑手参保，参保不依赖个人自愿登记。"),
    who: L("Riders, platforms, local social-security funds.", "骑手、平台、地方社保基金。"),
    influence: L("Demonstrated that mandatory, platform-administered coverage solves the voluntary take-up failure.", "表明强制、由平台代办的覆盖能解决自愿参保不足。"),
    importance: L("Evidence that the design scales — the key input to the 2025 decision.", "该设计可扩展的证据——2025 年决策的关键依据。"),
  },
  {
    date: "Jul 2025", kind: "milestone",
    title: L("Nine ministries expand the scheme; ~12.3m enrolled", "九部门扩大方案；参保约 1,234 万"),
    detail: L("Cumulative enrolment 12,345,700 by mid-2025.", "截至 2025 年年中累计参保 1,234.57 万。"),
    what: L("Nine central departments jointly issued a notice to expand occupational-injury coverage, by which point cumulative enrolment had reached about 12.35 million.", "九个中央部门联合发文扩大职业伤害保障覆盖，此时累计参保已达约 1,234.57 万。"),
    why: L("Strong pilot results and continued political priority on worker welfare and stability.", "试点成效显著，且劳动者福利与稳定持续是政治优先项。"),
    who: L("MOHRSS, NDRC, Ministry of Finance, ACFTU and others; platforms; riders nationwide.", "人社部、发改委、财政部、全国总工会等；平台；全国骑手。"),
    influence: L("Sets the stage for nationwide rollout and raises the question of extending beyond injury to pension and medical.", "为全国推开铺路，并提出从工伤扩展至养老与医疗的问题。"),
    importance: L("The event at the centre of this workspace — the moment coverage becomes near-universal in scope.", "本工作台的核心事件——覆盖在范围上接近普惠的时刻。"),
  },
  {
    date: "2026 →", kind: "future",
    title: L("Nationwide rollout; debate shifts to pension & medical", "全国推开；辩论转向养老与医疗"),
    detail: L("Cost incidence and full social-insurance extension become the live questions.", "成本归宿与完整社保扩展成为现实议题。"),
    what: L("With nationwide injury coverage planned, attention turns to whether platforms should also fund pension and medical insurance, and who ultimately bears the cost.", "在全国工伤覆盖计划推进之际，焦点转向平台是否也应为养老与医疗出资，以及成本最终由谁承担。"),
    why: L("Injury insurance addresses only one risk; old-age and health coverage remain the larger gap.", "工伤保险只覆盖一种风险；养老与健康覆盖仍是更大缺口。"),
    who: L("Policymakers, platforms, riders, consumers, and public funds.", "政策制定者、平台、骑手、消费者与公共基金。"),
    influence: L("Will determine whether China builds a portable, platform-funded model that other countries may emulate.", "将决定中国是否建立可携带、由平台出资的模式，供他国借鉴。"),
    importance: L("The forward-looking core of any essay: the reform is mid-stream, so the analysis shapes a live policy choice.", "任何论文的前瞻核心：改革正在进行中，分析因此影响一个现实政策选择。"),
  },
];

export const deliveryStakeholders: CaseStakeholder[] = [
  {
    id: "government", name: L("Government", "政府"), icon: "🏛",
    summary: L("Wants worker protection and social stability without crushing a major employer of low-skilled labour.", "希望在不压垮一个吸纳大量低技能劳动力的雇主的前提下保护劳动者并维护社会稳定。"),
    goals: L("Close the coverage gap, reduce public health/pension burden, preserve employment and stability.", "弥合覆盖缺口，减轻公共医疗／养老负担，保住就业与稳定。"),
    benefit: L("Legitimacy, lower uninsured-accident costs, a model exportable to other gig sectors.", "合法性、更低的未保险事故成本、可推广至其他零工行业的范本。"),
    cost: L("Administrative complexity; risk of slowing a job-creating sector if mandates are too heavy.", "行政复杂性；若强制过重，有拖慢创造就业部门的风险。"),
    incentives: L("Visible protection wins public support; phased injury-first design limits backlash.", "显性保护赢得公众支持；分阶段、工伤优先的设计限制反弹。"),
    conflicts: L("With platforms over who pays and how fast coverage expands.", "与平台在“谁出钱、覆盖扩展多快”上存在冲突。"),
    shared: L("With riders and unions on the goal of basic security.", "与骑手及工会在“基本保障”目标上一致。"),
  },
  {
    id: "platforms", name: L("Platform Companies", "平台企业"), icon: "🏭",
    summary: L("Meituan and Ele.me want to limit labour costs and preserve the flexible contractor model.", "美团与饿了么希望控制用工成本并保留灵活的承包人模式。"),
    goals: L("Protect margins, retain flexible supply, avoid full reclassification to employees.", "保护利润率，保留灵活供给，避免完全重新归类为雇员。"),
    benefit: L("Per-order injury insurance is cheaper and more predictable than employee status.", "按单工伤保险比雇员身份更便宜、更可预期。"),
    cost: L("New contributions raise costs; full pension/medical mandates would be far larger.", "新增缴费抬高成本；完整养老／医疗强制规定的成本会大得多。"),
    incentives: L("Accept limited injury cover to pre-empt tougher reclassification rules.", "接受有限的工伤覆盖以预先化解更严的重新归类规则。"),
    conflicts: L("With government over cost-sharing; with riders over pay pass-through.", "与政府在成本分担上、与骑手在收入转嫁上冲突。"),
    shared: L("With consumers on keeping delivery affordable.", "与消费者在“保持配送可负担”上一致。"),
  },
  {
    id: "riders", name: L("Delivery Riders", "外卖骑手"), icon: "🛵",
    summary: L("Want security against injury and old age — but also fear lower take-home pay and lost flexibility.", "希望获得工伤与养老保障——但也担心到手收入下降与失去灵活性。"),
    goals: L("Income stability, protection from catastrophic injury cost, retained flexible hours.", "收入稳定、免于灾难性工伤成本、保留灵活工时。"),
    benefit: L("Insurance covers accidents and builds pension entitlement.", "保险覆盖事故并积累养老金权益。"),
    cost: L("Possible lower piece-rates if platforms pass costs back; reduced casual entry.", "若平台转嫁成本，计件工资可能下降；临时进入减少。"),
    incentives: L("Value cover more when injury risk is high; value flexibility when it is the only available work.", "工伤风险高时更看重保障；当外卖是唯一可得工作时更看重灵活性。"),
    conflicts: L("With platforms over pay; among themselves (full-time vs casual) over what they want.", "与平台在收入上冲突；骑手之间（全职 对 临时）在诉求上分歧。"),
    shared: L("With government and unions on basic protection.", "与政府及工会在基本保护上一致。"),
  },
  {
    id: "consumers", name: L("Consumers", "消费者"), icon: "🛒",
    summary: L("Want cheap, fast delivery; may accept modest fee rises if framed as rider welfare.", "希望便宜、快速的配送；若与骑手福利挂钩，可能接受适度涨价。"),
    goals: L("Low delivery fees, fast service, reliable supply.", "低配送费、快速服务、可靠供给。"),
    benefit: L("A safer, more stable rider workforce can improve service quality.", "更安全、更稳定的骑手队伍可提升服务质量。"),
    cost: L("Part of any mandate cost can pass through to delivery fees.", "强制成本的一部分可转嫁至配送费。"),
    incentives: L("Willingness to pay rises with sympathy for riders, falls with price sensitivity.", "支付意愿随对骑手的同情上升、随价格敏感性下降。"),
    conflicts: L("With riders/platforms if fees rise sharply.", "若费用大幅上涨，与骑手／平台冲突。"),
    shared: L("With platforms on keeping the service affordable.", "与平台在“保持服务可负担”上一致。"),
  },
  {
    id: "unions", name: L("Labour Unions (ACFTU)", "工会（全国总工会）"), icon: "🤝",
    summary: L("The ACFTU pushes to organise riders and secure protections within the state framework.", "全国总工会推动组织骑手并在国家框架内争取保护。"),
    goals: L("Extend membership and protections to platform workers; channel grievances institutionally.", "将会员资格与保护扩展至平台劳动者；以制度化方式疏导诉求。"),
    benefit: L("Relevance and reach into a huge new workforce.", "对庞大新劳动群体的影响力与触达。"),
    cost: L("Limited leverage where riders are dispersed and classified as contractors.", "在骑手分散且被归类为承包人之处议价力有限。"),
    incentives: L("Co-signing platform agreements (e.g. Ele.me 2025) demonstrates results.", "联署平台协议（如饿了么 2025）以展示成效。"),
    conflicts: L("With platforms over bargaining scope.", "与平台在协商范围上冲突。"),
    shared: L("With government and riders on expanding protection.", "与政府及骑手在扩大保护上一致。"),
  },
  {
    id: "investors", name: L("Investors", "投资者"), icon: "📈",
    summary: L("Hold platform equity; care about how mandated costs hit margins and valuations.", "持有平台股权；关注强制成本如何影响利润率与估值。"),
    goals: L("Protect profitability and predictable regulation.", "保护盈利能力与可预期的监管。"),
    benefit: L("Clear, phased rules reduce regulatory uncertainty.", "清晰、分阶段的规则降低监管不确定性。"),
    cost: L("Higher labour costs compress margins, especially if extended to pension/medical.", "更高用工成本压缩利润率，尤其在扩展至养老／医疗时。"),
    incentives: L("Prefer limited, predictable injury cover over open-ended reclassification risk.", "相较开放式重新归类风险，更偏好有限、可预期的工伤覆盖。"),
    conflicts: L("With government/unions over the pace and scope of mandates.", "与政府／工会在强制的节奏与范围上冲突。"),
    shared: L("With platforms on cost discipline.", "与平台在成本约束上一致。"),
  },
];

export const deliveryRelations: CaseRelation[] = [
  { a: "government", b: "platforms", kind: "conflict", note: L("Who pays for coverage and how fast it expands.", "由谁为覆盖出资、扩展多快。") },
  { a: "riders", b: "platforms", kind: "conflict", note: L("Cost pass-through to piece-rates vs platform margins.", "成本向计件工资转嫁 对 平台利润率。") },
  { a: "consumers", b: "platforms", kind: "ally", note: L("Both want delivery to stay affordable.", "双方都希望配送保持可负担。") },
  { a: "government", b: "riders", kind: "ally", note: L("Shared goal of basic security and stability.", "在基本保障与稳定上目标一致。") },
  { a: "unions", b: "riders", kind: "ally", note: L("Unions seek to represent and protect riders.", "工会寻求代表并保护骑手。") },
  { a: "unions", b: "platforms", kind: "conflict", note: L("Bargaining scope and algorithm/labour rules.", "协商范围与算法／劳动规则。") },
  { a: "investors", b: "government", kind: "conflict", note: L("Pace and scope of mandated costs.", "强制成本的节奏与范围。") },
  { a: "investors", b: "platforms", kind: "ally", note: L("Both favour cost discipline and predictable rules.", "双方都倾向成本约束与可预期规则。") },
];
