import { CaseStudy, L, LS } from "./types";

export const evTariffs: CaseStudy = {
  id: "ev-tariffs",
  category: "trade",
  event: L("US raises tariffs on Chinese electric vehicles to 100%", "美国将中国电动汽车关税上调至 100%"),
  score: 94,
  potential: [
    { label: L("Theory richness", "理论丰富度"), value: 95 },
    { label: L("Data availability", "数据可得性"), value: 90 },
    { label: L("Debate / contestability", "争议性"), value: 96 },
    { label: L("Policy relevance", "政策相关性"), value: 97 },
  ],
  summary: {
    oneLine: L(
      "A 100% US tariff on Chinese EVs is a protectionist response to overcapacity that trades consumer welfare and the green transition for strategic and political goals.",
      "美国对中国电动车征收 100% 关税，是对产能过剩的保护主义回应，以消费者福利与绿色转型换取战略与政治目标。"
    ),
    overview: L(
      "The tariff quadruples the landed price of imported Chinese EVs. Standard trade theory predicts a net welfare loss for the importing country — a deadweight loss from reduced consumption and inefficient domestic production — partly offset by protected jobs, tariff revenue and any value placed on strategic autonomy or security externalities. The size and sign of the net effect depend on import demand elasticity, the credibility of retaliation, and how quickly domestic and third-country supply can substitute.",
      "该关税使进口中国电动车的到岸价格翻两番。标准贸易理论预测进口国会出现净福利损失——来自消费减少与本国低效生产的无谓损失——这部分被受保护的就业、关税收入以及对战略自主或安全外部性的赋值所抵消。净效应的大小与方向取决于进口需求弹性、报复的可信度，以及本国与第三国供给替代的速度。"
    ),
    matters: LS(
      ["It is a textbook clash between free-trade efficiency and industrial / national-security strategy.", "这是自由贸易效率与产业／国家安全战略之间的教科书式冲突。"],
      ["It directly raises EV prices and may slow decarbonisation in the importing market.", "它直接抬高电动车价格，可能拖慢进口市场的脱碳进程。"],
      ["It is a live, quantifiable case of tariffs, deadweight loss and retaliation risk.", "这是关税、无谓损失与报复风险的现实且可量化案例。"],
    ),
    stakeholders: LS(["Domestic automakers", "本国车企"], ["Chinese exporters", "中国出口商"], ["Consumers", "消费者"], ["Government", "政府"], ["Climate / EV adopters", "气候与电动车用户"]),
  },
  factors: [
    {
      key: "bg.economic",
      summary: L("Chinese EV overcapacity and steep cost advantages pressure Western producers.", "中国电动车产能过剩与显著成本优势对西方生产者形成压力。"),
      detail: L("Chinese manufacturers benefit from scale, an integrated battery supply chain and learning-curve effects, producing competitive EVs at prices Western firms struggle to match. Without barriers, import penetration would rise quickly, compressing domestic margins and market share.", "中国制造商受益于规模、一体化电池供应链与学习曲线效应，能以西方企业难以匹敌的价格生产具竞争力的电动车。若无壁垒，进口渗透率会迅速上升，压缩本国利润率与市场份额。"),
      statistics: LS(["Chinese EV export prices ~20–30% below Western equivalents", "中国电动车出口价较西方同类低约 20–30%"], ["China produced >60% of global EVs in recent years", "近年中国生产全球逾 60% 的电动车"]),
      stakeholders: LS(["Domestic automakers", "本国车企"], ["Battery suppliers", "电池供应商"]),
      essayIdeas: LS(["Is the tariff correcting 'unfair' subsidies or just blocking comparative advantage?", "关税是在纠正“不公平”补贴，还是仅在阻挡比较优势？"]),
      arguments: LS(["Protection buys time for domestic firms to reach scale.", "保护为本国企业达到规模争取时间。"]),
      counterarguments: LS(["Shielding inefficient producers entrenches high costs (infant-industry critique).", "庇护低效生产者会固化高成本（幼稚产业批评）。"]),
    },
    {
      key: "bg.political",
      summary: L("Tariffs are politically salient in election cycles and manufacturing regions.", "关税在选举周期与制造业地区具高度政治显著性。"),
      detail: L("Visible protection of domestic jobs is politically rewarding even when costs are diffuse; concentrated beneficiaries lobby hard while dispersed consumers rarely organise — a classic collective-action asymmetry.", "对本国就业的显性保护在政治上有回报，即使成本是分散的；集中的受益者强力游说，而分散的消费者很少组织起来——这是典型的集体行动不对称。"),
      statistics: LS(["Auto sector concentrated in a handful of swing regions", "汽车业集中于少数摇摆地区"]),
      stakeholders: LS(["Politicians", "政客"], ["Unions", "工会"]),
      essayIdeas: LS(["Apply public-choice theory: who captures trade policy?", "运用公共选择理论：谁俘获了贸易政策？"]),
      arguments: LS(["Democratic accountability justifies protecting voters' livelihoods.", "民主问责为保护选民生计提供正当性。"]),
      counterarguments: LS(["Policy may serve concentrated lobbies over national welfare.", "政策可能服务于集中游说集团而非国家福利。"]),
    },
    {
      key: "bg.technological",
      summary: L("EVs are strategic technology tied to batteries, chips and data.", "电动车是与电池、芯片与数据相关的战略技术。"),
      detail: L("Control of EV and battery manufacturing is framed as critical to future industrial capability and security, raising the perceived value of domestic capacity beyond pure market efficiency.", "对电动车与电池制造的掌控被视为未来产业能力与安全的关键，使本国产能的感知价值超出纯粹的市场效率。"),
      statistics: LS(["Batteries are ~30–40% of EV cost", "电池约占电动车成本的 30–40%"]),
      stakeholders: LS(["Defence / security agencies", "国防与安全机构"], ["Tech firms", "科技企业"]),
      essayIdeas: LS(["Model security as a positive externality of domestic production.", "把安全建模为本国生产的正外部性。"]),
      arguments: LS(["Strategic autonomy is a legitimate non-market objective.", "战略自主是正当的非市场目标。"]),
      counterarguments: LS(["Security can become a catch-all excuse for protectionism.", "安全可能沦为保护主义的万能借口。"]),
    },
    {
      key: "bg.environmental",
      summary: L("Higher EV prices may slow emissions reductions.", "更高的电动车价格可能拖慢减排。"),
      detail: L("If tariffs raise EV prices and reduce uptake, the climate cost is a negative externality of the policy — a tension between industrial protection and decarbonisation goals.", "若关税抬高电动车价格并抑制采纳，气候成本就是该政策的负外部性——这是产业保护与脱碳目标之间的张力。"),
      statistics: LS(["Transport is ~15–25% of national emissions in many economies", "在许多经济体中交通占国家排放约 15–25%"]),
      stakeholders: LS(["Climate-policy bodies", "气候政策机构"], ["EV adopters", "电动车用户"]),
      essayIdeas: LS(["Quantify the carbon opportunity cost of slower EV adoption.", "量化电动车采纳放缓的碳机会成本。"]),
      arguments: LS(["Domestic green industry can still decarbonise long-term.", "本国绿色产业长期仍可脱碳。"]),
      counterarguments: LS(["Cheaper imports would cut emissions faster now.", "更便宜的进口能在当下更快减排。"]),
    },
    {
      key: "bg.legal",
      summary: L("Tariffs interact with WTO rules and trade-remedy law.", "关税与 WTO 规则及贸易救济法相互作用。"),
      detail: L("Measures must be justified under anti-subsidy, anti-dumping or security exceptions; mis-framing invites disputes and authorised retaliation.", "措施须依反补贴、反倾销或安全例外加以正当化；错误定性会招致争端与被授权的报复。"),
      statistics: LS(["WTO disputes can take years to resolve", "WTO 争端可能需数年才能解决"]),
      stakeholders: LS(["Trade lawyers", "贸易律师"], ["WTO / partners", "WTO 与伙伴"]),
      essayIdeas: LS(["Is the security exception being used legitimately?", "安全例外是否被正当使用？"]),
      arguments: LS(["Rules permit defence against subsidised dumping.", "规则允许抵御受补贴的倾销。"]),
      counterarguments: LS(["Unilateral tariffs erode the rules-based system.", "单边关税侵蚀基于规则的体系。"]),
    },
    {
      key: "bg.social",
      summary: L("Distributional impact: manufacturing workers vs car buyers.", "分配影响：制造业工人 对 购车者。"),
      detail: L("Protected workers gain job security; consumers — disproportionately lower-income — face higher prices and less choice. Incidence depends on pass-through.", "受保护的工人获得就业保障；消费者（其中低收入者占比更高）面临更高价格与更少选择。归宿取决于价格转嫁程度。"),
      statistics: LS(["Cars are a large share of household durable spending", "汽车占家庭耐用品支出较大比重"]),
      stakeholders: LS(["Workers", "工人"], ["Low-income consumers", "低收入消费者"]),
      essayIdeas: LS(["Run an incidence analysis of who bears the tariff.", "做一项关税归宿分析。"]),
      arguments: LS(["Protecting jobs supports communities.", "保护就业有助于社区。"]),
      counterarguments: LS(["Regressive price effects outweigh narrow job gains.", "累退的价格效应超过狭隘的就业收益。"]),
    },
    {
      key: "bg.historical",
      summary: L("Echoes earlier auto and steel protection episodes.", "呼应早前的汽车与钢铁保护事件。"),
      detail: L("Historical voluntary export restraints and steel tariffs offer evidence on price effects, employment and retaliation — useful comparators.", "历史上的自愿出口限制与钢铁关税为价格效应、就业与报复提供了证据——是有用的对照。"),
      statistics: LS(["1980s auto VERs raised US car prices measurably", "1980 年代汽车自愿出口限制明显抬高美国车价"]),
      stakeholders: LS(["Economic historians", "经济史学者"]),
      essayIdeas: LS(["Use historical tariffs as a natural experiment.", "把历史关税当作自然实验。"]),
      arguments: LS(["Past protection sometimes preserved industries.", "过去的保护有时保住了产业。"]),
      counterarguments: LS(["It often raised prices without lasting competitiveness.", "它常抬高价格却未带来持久竞争力。"]),
    },
    {
      key: "bg.cultural",
      summary: L("'Buy domestic' sentiment shapes legitimacy.", "“购买本国货”情绪影响合法性。"),
      detail: L("National pride in domestic manufacturing raises tolerance for higher prices and frames imports as a threat, affecting demand elasticity.", "对本国制造的民族自豪感提高了对更高价格的容忍度，并将进口塑造为威胁，从而影响需求弹性。"),
      statistics: LS(["Brand-of-origin effects influence car choice", "原产国品牌效应影响购车选择"]),
      stakeholders: LS(["Consumers", "消费者"], ["Media", "媒体"]),
      essayIdeas: LS(["How do preferences alter the welfare calculus?", "偏好如何改变福利计算？"]),
      arguments: LS(["Preferences are legitimate inputs to welfare.", "偏好是福利的正当输入。"]),
      counterarguments: LS(["Sentiment can mask real efficiency losses.", "情绪可能掩盖真实的效率损失。"]),
    },
  ],
  timeline: [
    { date: "2015–2020", kind: "cause", title: L("China scales EV & battery industry", "中国扩大电动车与电池产业"), detail: L("Sustained industrial policy builds dominant battery and EV manufacturing capacity and a steep cost curve.", "持续的产业政策建立了主导性的电池与电动车制造产能及陡峭的成本曲线。") },
    { date: "2023", kind: "cause", title: L("Export surge & overcapacity", "出口激增与产能过剩"), detail: L("Slowing domestic demand pushes Chinese EV exports outward, alarming Western producers.", "本国需求放缓推动中国电动车向外出口，令西方生产者警觉。") },
    { date: "2024", kind: "trigger", title: L("Initial tariff hikes announced", "宣布初步加征关税"), detail: L("Anti-subsidy investigations and first duty increases signal escalation.", "反补贴调查与首轮加征关税预示升级。") },
    { date: "2026-06", kind: "milestone", title: L("Tariff raised to 100%", "关税上调至 100%"), detail: L("A headline 100% duty effectively prices most Chinese EVs out of the market.", "标志性的 100% 关税实际上将大多数中国电动车挤出市场。") },
    { date: "2026-2027", kind: "future", title: L("Retaliation & supply-chain rerouting", "报复与供应链改道"), detail: L("Likely countermeasures on other goods; Chinese firms may localise via third countries (e.g. assembly abroad).", "对其他商品的可能反制；中国企业或经第三国本地化（如海外组装）。") },
    { date: "2028+", kind: "future", title: L("Domestic capacity & price equilibrium", "本国产能与价格均衡"), detail: L("Whether protected firms reach competitive scale, or prices stay structurally higher, decides the long-run verdict.", "受保护企业能否达到竞争性规模，抑或价格结构性偏高，将决定长期结论。") },
  ],
  theories: [
    { name: L("International Trade Theory", "国际贸易理论"), match: 97, diagram: "supplyDemand", explanation: L("Free trade lets each country specialise where it is relatively most efficient, expanding total output and consumption.", "自由贸易使各国专注于相对最有效率的领域，从而扩大总产出与消费。"), relevance: L("A tariff blocks gains from trade, moving the importer inside its consumption-possibility frontier.", "关税阻断贸易收益，使进口国退回到其消费可能性边界之内。"), strengths: LS(["Quantifiable welfare predictions", "可量化的福利预测"], ["Strong empirical support", "强实证支持"]), weaknesses: LS(["Assumes adjustment is costless", "假设调整无成本"], ["Ignores strategic externalities", "忽略战略外部性"]) },
    { name: L("Comparative Advantage", "比较优势"), match: 95, diagram: "ppc", explanation: L("Even an absolutely more productive country gains by importing goods others produce at lower opportunity cost.", "即使绝对生产率更高的国家，通过进口他国以更低机会成本生产的商品仍能获益。"), relevance: L("If China's opportunity cost in EVs is lower, blocking imports forgoes mutual gains.", "若中国在电动车上的机会成本更低，阻断进口便放弃了互利收益。"), strengths: LS(["Explains why trade is positive-sum", "解释贸易为何是正和的"]), weaknesses: LS(["Static; ignores dynamic / strategic sectors", "静态；忽略动态与战略性部门"]) },
    { name: L("Protectionism & Deadweight Loss", "保护主义与无谓损失"), match: 93, diagram: "supplyDemand", explanation: L("A tariff raises price above the world level, cutting consumer surplus by more than producer surplus and revenue gains — leaving a deadweight loss.", "关税将价格抬高于世界水平，消费者剩余的损失超过生产者剩余与收入收益之和——形成无谓损失。"), relevance: L("The two welfare triangles measure the efficiency cost of the 100% duty.", "两个福利三角形衡量了 100% 关税的效率成本。"), strengths: LS(["Pinpoints the efficiency cost", "精确指出效率成本"]), weaknesses: LS(["Partial-equilibrium; ignores spillovers", "局部均衡；忽略外溢"]) },
    { name: L("Infant Industry Argument", "幼稚产业论"), match: 84, diagram: "costCurves", explanation: L("Temporary protection can let a young industry reach the scale where its costs fall to world levels.", "暂时保护可使新兴产业达到成本降至世界水平的规模。"), relevance: L("The core pro-tariff case — valid only if firms truly become competitive and protection is withdrawn.", "支持关税的核心论点——仅当企业真正具备竞争力且保护被撤销时才成立。"), strengths: LS(["Justifies temporary intervention", "为暂时干预辩护"]), weaknesses: LS(["Protection rarely sunset; risk of permanent rents", "保护很少退出；存在永久租金风险"]) },
    { name: L("Strategic Trade / Externalities", "战略性贸易／外部性"), match: 80, diagram: "externalities", explanation: L("When production yields security or knowledge spillovers, the social value of domestic output exceeds its private value.", "当生产带来安全或知识溢出时，本国产出的社会价值高于其私人价值。"), relevance: L("Provides the strongest non-protectionist rationale for supporting domestic EVs.", "为支持本国电动车提供了最强的非保护主义理由。"), strengths: LS(["Captures security & innovation value", "刻画安全与创新价值"]), weaknesses: LS(["Externalities hard to measure; capture risk", "外部性难以测量；存在被俘获风险"]) },
    { name: L("Public Choice Theory", "公共选择理论"), match: 76, diagram: "supplyDemand", explanation: L("Concentrated producers lobby for protection while diffuse consumers bear small individual costs.", "集中的生产者游说保护，而分散的消费者各自承担较小成本。"), relevance: L("Explains why a welfare-reducing tariff can still be politically optimal.", "解释为何降低福利的关税在政治上仍可能最优。"), strengths: LS(["Realistic political economy", "贴近现实的政治经济学"]), weaknesses: LS(["Can be overly cynical", "可能过于犬儒"]) },
  ],
  counter: [
    { a: L("Free Trade", "自由贸易"), b: L("Protectionism", "保护主义"), tension: L("Do the gains from cheaper EVs and trade outweigh the loss of strategic domestic capacity?", "更便宜的电动车与贸易收益，是否超过失去本国战略产能的损失？") },
    { a: L("Comparative Advantage", "比较优势"), b: L("Strategic Trade", "战略性贸易"), tension: L("Should policy follow static efficiency, or shape dynamic advantage in a key sector?", "政策应遵循静态效率，还是塑造关键部门的动态优势？") },
  ],
  methods: [
    { name: L("Partial-Equilibrium Tariff Welfare Analysis", "局部均衡关税福利分析"), fit: 95, purpose: L("Measure deadweight loss, revenue and surplus shifts from the tariff.", "测量关税带来的无谓损失、收入与剩余转移。"), formula: "DWL = ½ · Δt · ΔQ ;  Revenue = t · Q_imports", assumptions: L("Known elasticities; small distortions elsewhere.", "已知弹性；他处扭曲较小。"), data: L("Import volumes, prices, demand & supply elasticities.", "进口量、价格、供给与需求弹性。"), advantages: L("Directly quantifies the welfare triangles.", "直接量化福利三角。"), weaknesses: L("Ignores general-equilibrium and retaliation.", "忽略一般均衡与报复。") },
    { name: L("Gravity Model of Trade", "贸易引力模型"), fit: 88, purpose: L("Estimate how the tariff reshapes bilateral trade flows.", "估计关税如何重塑双边贸易流。"), formula: "ln(X_ij) = β₀ + β₁ ln(GDP_i·GDP_j) − β₂ ln(dist) + β₃ Tariff + ε", assumptions: L("Stable trade frictions; exogenous policy.", "贸易摩擦稳定；政策外生。"), data: L("Bilateral trade, GDP, distance, tariff schedules.", "双边贸易、GDP、距离、关税表。"), advantages: L("Empirically robust workhorse of trade.", "贸易领域稳健的主力模型。"), weaknesses: L("Reduced-form; weak on welfare.", "简约式；对福利刻画弱。") },
    { name: L("Difference-in-Differences", "双重差分"), fit: 86, purpose: L("Compare EV prices/sales pre- vs post-tariff against unaffected segments.", "对比受影响与未受影响细分市场在关税前后的价格／销量。"), formula: "Y = β₀ + β₁Treat + β₂Post + β₃(Treat·Post) + ε", assumptions: L("Parallel trends absent the tariff.", "无关税时趋势平行。"), data: L("Model-level price & registration panel.", "车型级价格与上牌面板数据。"), advantages: L("Credible causal pass-through estimate.", "可信的因果价格转嫁估计。"), weaknesses: L("Confounded by simultaneous shocks.", "受同期冲击混淆。") },
    { name: L("Computable General Equilibrium (CGE)", "可计算一般均衡（CGE）"), fit: 78, purpose: L("Trace economy-wide and cross-sector effects incl. retaliation.", "追踪含报复在内的全经济与跨部门效应。"), formula: "Solve {supply=demand} across all markets given policy shock", assumptions: L("Specified substitution elasticities; market clearing.", "设定替代弹性；市场出清。"), data: L("Input–output tables, trade elasticities.", "投入产出表、贸易弹性。"), advantages: L("Captures linkages and feedback.", "刻画联系与反馈。"), weaknesses: L("Sensitive to calibration assumptions.", "对校准假设敏感。") },
  ],
  datasets: [
    { name: "UN Comtrade (bilateral trade)", provider: "United Nations", url: "https://comtrade.un.org" },
    { name: "WITS Tariff Data", provider: "World Bank", url: "https://wits.worldbank.org" },
    { name: "OECD Inter-Country Input-Output", provider: "OECD", url: "https://www.oecd.org/sti/ind/inter-country-input-output-tables.htm" },
    { name: "IEA Global EV Outlook", provider: "IEA", url: "https://www.iea.org/reports/global-ev-outlook-2024" },
    { name: "FRED Motor Vehicle CPI", provider: "Federal Reserve", url: "https://fred.stlouisfed.org" },
  ],
  evidence: [
    {
      title: L("Global EV Outlook (production, prices, trade)", "全球电动车展望（产量、价格、贸易）"),
      publisher: "IEA", grade: "A+", reliability: 95, bias: L("Low · energy-transition framing", "低 · 能源转型视角"),
      requiredData: L("EV output, export volumes, average prices by region.", "各地区电动车产量、出口量、平均价格。"),
      whyItMatters: L("Establishes the cost gap and import-penetration trend the tariff targets.", "确立关税所针对的成本差距与进口渗透趋势。"),
      howItSupports: L("Quantifies the size of the shock for the welfare and gravity models.", "为福利与引力模型量化冲击规模。"),
      url: "https://www.iea.org/reports/global-ev-outlook-2024", year: 2024,
    },
    {
      title: L("WITS tariff schedules & trade flows", "WITS 关税表与贸易流"),
      publisher: "World Bank", grade: "A+", reliability: 96, bias: L("Minimal · primary administrative data", "极低 · 一手行政数据"),
      requiredData: L("MFN & applied tariff lines, bilateral import values.", "最惠国与实施关税税目、双边进口额。"),
      whyItMatters: L("The policy variable itself — needed to compute revenue and pass-through.", "政策变量本身——计算收入与转嫁所必需。"),
      howItSupports: L("Feeds t and Q into DWL = ½·Δt·ΔQ.", "为 DWL = ½·Δt·ΔQ 提供 t 与 Q。"),
      url: "https://wits.worldbank.org", year: 2026,
    },
    {
      title: L("Peer-reviewed estimates of tariff pass-through", "关税转嫁的同行评审估计"),
      publisher: "American Economic Review", grade: "A", reliability: 90, bias: L("Low · publication bias possible", "低 · 可能存在发表偏倚"),
      requiredData: L("Price series before/after comparable tariff episodes.", "可比关税事件前后的价格序列。"),
      whyItMatters: L("Shows how much of the duty reaches consumers vs is absorbed.", "显示关税多少传导至消费者、多少被吸收。"),
      howItSupports: L("Calibrates the incidence and DWL estimates.", "校准归宿与无谓损失估计。"),
      url: "https://www.aeaweb.org/journals/aer", year: 2020,
    },
    {
      title: L("Industry EV market outlook", "行业电动车市场展望"),
      publisher: "BloombergNEF", grade: "B", reliability: 74, bias: L("Moderate · commercial clientele", "中等 · 商业客户导向"),
      requiredData: L("Forecast adoption, battery cost curves.", "采纳预测、电池成本曲线。"),
      whyItMatters: L("Projects future prices and the climate opportunity cost.", "预测未来价格与气候机会成本。"),
      howItSupports: L("Informs long-run scenarios and CGE shocks.", "为长期情景与 CGE 冲击提供输入。"),
      url: "https://about.bnef.com", year: 2025,
    },
    {
      title: L("News coverage of the tariff announcement", "关税公告的新闻报道"),
      publisher: "Reuters", grade: "C", reliability: 58, bias: L("Editorial framing; timely but thin", "编辑取向；及时但单薄"),
      requiredData: L("Official statements, dates, headline rates.", "官方声明、日期、标题税率。"),
      whyItMatters: L("Confirms the policy event and timing for the DiD.", "为双重差分确认政策事件与时点。"),
      howItSupports: L("Defines the treatment date; not a source for magnitudes.", "界定处理时点；不作量级来源。"),
      url: "https://www.reuters.com", year: 2026,
    },
  ],
  literature: {
    supporting: [
      { cite: "Irwin (2020), Clashing over Commerce", finding: L("Historical tariffs typically reduced net welfare while protecting specific industries.", "历史关税通常在保护特定产业的同时降低净福利。"), stance: "support" },
      { cite: "Amiti, Redding & Weinstein (2019)", finding: L("Recent US tariffs were largely passed through to domestic prices.", "近期美国关税在很大程度上传导至本国价格。"), stance: "support" },
    ],
    opposing: [
      { cite: "Strategic-trade scholarship (Brander–Spencer lineage)", finding: L("In imperfect competition, well-targeted intervention can raise national welfare.", "在不完全竞争下，精准的干预可提升国家福利。"), stance: "oppose" },
      { cite: "Industrial-policy revival literature", finding: L("Protection plus conditions can build competitive green industries.", "保护加附加条件可培育有竞争力的绿色产业。"), stance: "oppose" },
    ],
    debates: LS(
      ["Static efficiency loss vs dynamic / strategic gains.", "静态效率损失 对 动态与战略收益。"],
      ["Whether 'national security' is an honest or pretextual justification.", "“国家安全”究竟是真实理由还是托词。"],
    ),
    authors: [
      { name: "Douglas Irwin", field: L("Trade history & policy", "贸易史与政策") },
      { name: "Pinelopi Goldberg", field: L("Trade & development", "贸易与发展") },
      { name: "Réka Juhász", field: L("Industrial policy", "产业政策") },
    ],
    gaps: LS(["Few causal estimates for EVs specifically.", "针对电动车的因果估计稀少。"], ["Climate cost of slower adoption is under-quantified.", "采纳放缓的气候成本量化不足。"]),
    future: LS(["DiD on model-level prices around the tariff date.", "围绕关税时点对车型级价格做双重差分。"], ["CGE with explicit retaliation scenarios.", "含明确报复情景的 CGE 分析。"]),
    consensus: 68,
  },
  proposals: [
    {
      id: "A", name: L("Targeted countervailing duty (not a blanket 100%)", "定向反补贴税（而非一刀切 100%）"),
      objective: L("Offset only the measured unfair subsidy, preserving most gains from trade.", "仅抵消所测得的不公平补贴，保留大部分贸易收益。"),
      cost: 2, impact: 3, fairness: 4, feasibility: 3, risk: 2,
      steps: LS(["Run a subsidy investigation to quantify the margin.", "开展补贴调查以量化补贴幅度。"], ["Set duty equal to the verified subsidy.", "将税率设为经核实的补贴。"], ["Review annually with a sunset clause.", "每年复核并设日落条款。"]),
      timeline: L("6–12 months to investigate; annual review.", "调查 6–12 个月；每年复核。"),
      budget: L("Administrative / investigatory cost only; raises some revenue.", "仅行政与调查成本；带来部分收入。"),
      stakeholderResponses: [{ who: L("Trade partners", "贸易伙伴"), reaction: L("More WTO-defensible; lower retaliation risk.", "更具 WTO 可辩护性；报复风险更低。") }, { who: L("Domestic firms", "本国企业"), reaction: L("Less protection than a 100% wall.", "保护力度低于 100% 的壁垒。") }],
      risks: LS(["Subsidy hard to measure precisely.", "补贴难以精确测量。"]),
      alternatives: LS(["Blanket tariff (Proposal C).", "一刀切关税（方案 C）。"]),
      metrics: LS(["Import price change vs subsidy margin.", "进口价格变动 对 补贴幅度。"], ["WTO challenge outcomes.", "WTO 诉讼结果。"]),
    },
    {
      id: "B", name: L("Subsidise domestic EV & battery production", "补贴本国电动车与电池生产"),
      objective: L("Build competitiveness via production subsidies/tax credits instead of import barriers.", "以生产补贴／税收抵免而非进口壁垒建立竞争力。"),
      cost: 4, impact: 4, fairness: 3, feasibility: 3, risk: 3,
      steps: LS(["Offer per-unit or capex credits tied to output & jobs.", "提供与产量及就业挂钩的单位或资本支出抵免。"], ["Fund battery R&D and supply chain.", "资助电池研发与供应链。"], ["Phase out as costs fall.", "随成本下降逐步退出。"]),
      timeline: L("2–5 years to scale capacity.", "2–5 年扩大产能。"),
      budget: L("Large fiscal outlay; on-budget and visible.", "较大财政支出；列入预算且可见。"),
      stakeholderResponses: [{ who: L("Consumers", "消费者"), reaction: L("Keeps EV prices low — climate-friendly.", "维持电动车低价——利于气候。") }, { who: L("Taxpayers", "纳税人"), reaction: L("Bear the cost; demand accountability.", "承担成本；要求问责。") }],
      risks: LS(["Fiscal cost; risk of subsidy race.", "财政成本；补贴竞赛风险。"]),
      alternatives: LS(["Tariff protection (Proposal C).", "关税保护（方案 C）。"]),
      metrics: LS(["Domestic cost per kWh over time.", "本国每千瓦时成本随时间变化。"], ["Jobs and output per dollar spent.", "每美元支出对应的就业与产出。"]),
    },
    {
      id: "C", name: L("Blanket 100% tariff (status quo policy)", "一刀切 100% 关税（现状政策）"),
      objective: L("Maximally shield domestic producers and strategic capacity.", "最大程度庇护本国生产者与战略产能。"),
      cost: 3, impact: 4, fairness: 2, feasibility: 4, risk: 4,
      steps: LS(["Impose duty across all Chinese EV imports.", "对所有中国电动车进口征税。"], ["Pair with anti-circumvention rules.", "配套反规避规则。"]),
      timeline: L("Immediate effect.", "立即生效。"),
      budget: L("Raises tariff revenue but imposes consumer cost.", "带来关税收入但施加消费者成本。"),
      stakeholderResponses: [{ who: L("Chinese exporters", "中国出口商"), reaction: L("Reroute via third countries; retaliate.", "经第三国改道；进行报复。") }, { who: L("Consumers", "消费者"), reaction: L("Higher prices, less choice.", "价格更高、选择更少。") }],
      risks: LS(["Deadweight loss; retaliation; slower decarbonisation.", "无谓损失；报复；脱碳放缓。"]),
      alternatives: LS(["Targeted duty (Proposal A).", "定向关税（方案 A）。"]),
      metrics: LS(["Net welfare incl. revenue & DWL.", "含收入与无谓损失的净福利。"], ["Retaliation value on exports.", "出口遭报复的价值。"]),
    },
  ],
  critical: [
    { key: "ce.shortRun", text: L("Imported-EV prices jump immediately; domestic firms gain share and consumers lose surplus.", "进口电动车价格立即跳升；本国企业获得份额，消费者损失剩余。") },
    { key: "ce.longRun", text: L("If domestic costs fall to world levels, protection may be vindicated; if not, prices stay structurally high.", "若本国成本降至世界水平，保护或被证明合理；否则价格将结构性偏高。") },
    { key: "ce.intended", text: L("Protect strategic auto/battery capacity and jobs from subsidised competition.", "保护战略性汽车／电池产能与就业，免受受补贴竞争冲击。") },
    { key: "ce.unintended", text: L("Retaliation, third-country rerouting, higher prices, and slower EV adoption.", "报复、经第三国改道、价格上涨与电动车采纳放缓。") },
    { key: "ce.equity", text: L("Regressive: lower-income car buyers bear price rises; auto workers and shareholders gain.", "具累退性：低收入购车者承担涨价；汽车工人与股东获益。") },
    { key: "ce.sustainability", text: L("Tension with climate goals if EV uptake slows; aligned only if domestic green capacity scales fast.", "若电动车采纳放缓则与气候目标冲突；唯有本国绿色产能快速扩张才一致。") },
    { key: "ce.ethical", text: L("Weighs national interest and workers against global efficiency and consumers abroad.", "在国家利益与工人 对 全球效率与海外消费者之间权衡。") },
    { key: "ce.alternatives", text: L("Targeted countervailing duties or production subsidies may achieve goals at lower welfare cost.", "定向反补贴税或生产补贴或能以更低福利成本达成目标。") },
  ],
  essay: {
    basic: {
      rq: L("Are the US tariffs on Chinese EVs good or bad for the country?", "美国对中国电动车的关税对本国是利还是弊？"),
      thesis: L("The tariff protects some domestic jobs but raises prices for consumers, so its overall effect is mixed and probably negative for welfare.", "关税保护了部分本国就业，却抬高了消费者价格，因此其总体效应好坏参半，对福利而言很可能为负。"),
      outline: [
        { heading: L("Introduction", "引言"), points: LS(["Define a tariff and state the question.", "界定关税并提出问题。"]) },
        { heading: L("Point — domestic jobs", "论点——本国就业"), points: LS(["Tariff shields local carmakers (supply & demand diagram).", "关税庇护本地车企（供需图）。"]) },
        { heading: L("Point — higher prices", "论点——价格上涨"), points: LS(["Consumers pay more and buy fewer EVs.", "消费者付出更多并少买电动车。"]) },
        { heading: L("Conclusion", "结论"), points: LS(["Weigh both sides; give a simple judgement.", "权衡两面；给出简单判断。"]) },
      ],
      note: L("Simple two-sided structure with one diagram. Clear definitions over depth.", "简单的两面结构 + 一张图。重在清晰定义而非深度。"),
    },
    advanced: {
      rq: L("To what extent does a 100% tariff on Chinese EVs improve net economic welfare in the importing country?", "对中国电动车征收 100% 关税，在多大程度上提升进口国的净经济福利？"),
      thesis: L("Standard trade theory predicts a deadweight loss, but the net effect depends on import-demand elasticity, retaliation and the value of strategic externalities — so the tariff is justified only under restrictive conditions.", "标准贸易理论预测无谓损失，但净效应取决于进口需求弹性、报复与战略外部性价值——因此关税仅在严格条件下才合理。"),
      outline: [
        { heading: L("Introduction", "引言"), points: LS(["Define terms; set up the welfare framework.", "界定术语；搭建福利框架。"]) },
        { heading: L("Argument 1 — efficiency cost", "论点一——效率成本"), points: LS(["Tariff welfare diagram: surplus shifts + DWL.", "关税福利图：剩余转移 + 无谓损失。"], ["Evidence on pass-through.", "转嫁的证据。"], ["Counter: terms-of-trade gain for a large country.", "反驳：大国的贸易条件收益。"], ["Evaluate: depends on elasticities.", "评估：取决于弹性。"]) },
        { heading: L("Argument 2 — strategic & infant industry", "论点二——战略与幼稚产业"), points: LS(["Externalities/infant-industry case.", "外部性／幼稚产业论。"], ["Counter: protection rarely sunsets.", "反驳：保护很少退出。"]) },
        { heading: L("Argument 3 — distribution & climate", "论点三——分配与气候"), points: LS(["Regressive incidence; slower decarbonisation.", "累退归宿；脱碳放缓。"]) },
        { heading: L("Conclusion", "结论"), points: LS(["Conditional judgement tied to elasticities & retaliation.", "与弹性及报复挂钩的有条件判断。"]) },
      ],
      note: L("Three argument blocks, each with evidence, counter and evaluation. Multiple diagrams.", "三段论证，每段含证据、反驳与评估。多张图。"),
    },
    research: {
      rq: L("What is the net welfare effect of the US 100% EV tariff, and under what conditions is targeted industrial policy a superior instrument?", "美国 100% 电动车关税的净福利效应如何？在何种条件下定向产业政策是更优工具？"),
      thesis: L("Using a partial-equilibrium welfare model triangulated with gravity and CGE evidence, the blanket tariff likely produces a net welfare loss once retaliation and climate costs are internalised; a calibrated countervailing duty or production subsidy weakly dominates it across plausible elasticities.", "运用局部均衡福利模型，并以引力模型与 CGE 证据三角互证，一旦将报复与气候成本内部化，一刀切关税很可能产生净福利损失；在合理弹性范围内，经校准的反补贴税或生产补贴对其呈弱占优。"),
      outline: [
        { heading: L("Introduction & contribution", "引言与贡献"), points: LS(["Motivate; state the gap and contribution.", "立题；说明空白与贡献。"]) },
        { heading: L("Literature review", "文献综述"), points: LS(["Trade-cost vs strategic-trade vs industrial-policy schools.", "贸易成本派 对 战略性贸易派 对 产业政策派。"]) },
        { heading: L("Theoretical framework", "理论框架"), points: LS(["Welfare model with externality term and retaliation.", "含外部性项与报复的福利模型。"]) },
        { heading: L("Methodology", "方法"), points: LS(["Partial-eq calibration; gravity & DiD identification; CGE robustness.", "局部均衡校准；引力与双重差分识别；CGE 稳健性。"]) },
        { heading: L("Results & policy evaluation", "结果与政策评估"), points: LS(["Compare instruments on welfare, equity, climate, feasibility.", "在福利、公平、气候、可行性上比较各工具。"]) },
        { heading: L("Limitations & research gaps", "局限与研究空白"), points: LS(["Elasticity uncertainty; unmodelled dynamics.", "弹性不确定性；未建模的动态。"]) },
      ],
      note: L("Full academic structure: literature integration, explicit methodology, identification strategy, policy evaluation and research gaps.", "完整学术结构：文献整合、明确方法、识别策略、政策评估与研究空白。"),
    },
  },
};
